In this file we connect the institutions to the cultural and geopolitical distance metrics. This will allow for easier plotting later. 
The end goal is to export the institutions with the new cultural / geopolitical dimensions. After this we will build an interactive data visualization which demonstrates the distance between instituitions and countries working in similar topics with links connecting those who are collaborating.

In [25]:
import pandas as pd

# Define the path to the .dta file
file_path = './data/cultural_distance_PSW2024.dta'

# Load the .dta file into a DataFrame
cultural_distance_df = pd.read_stata(file_path)

# Display the first few rows of the DataFrame
cultural_distance_df.head()

   year countrycode_1 countrycode_2  cultdist  cultdist_std  n_questions
0  1984           ALB           ALB  0.279388     -2.574591          320
1  1993           ALB           ALB  0.279218     -2.582615          320
2  1998           ALB           ALB  0.279133     -2.586663          320
3  2002           ALB           ALB  0.289996     -2.076870          320
4  2009           ALB           ALB  0.296838     -1.761543          320

In [26]:
# Select the rows with the most recent year for each countrycode_1
most_recent_results = cultural_distance_df.loc[cultural_distance_df.groupby('countrycode_1')['year'].idxmax()]

# Display the resulting DataFrame
most_recent_results.head()

      year countrycode_1 countrycode_2  cultdist  cultdist_std  n_questions
6     2021           ALB           ALB  0.261209     -3.455396          320
818   2021           AND           ALB  0.322753     -0.603146          160
1630  2021           ARG           ALB  0.318365     -0.795609          276
2442  2021           ARM           ALB  0.301791     -1.535909          300
3254  2021           AUS           ALB  0.348296      0.491817          207

In [27]:
# Import pandas
import pandas as pd

# Define the path to the CSV file
geo_file_path = './Data/dataverse_files/IdealpointestimatesAll_Jun2024.csv'

# Load the CSV file into a DataFrame
geopolitical_distance_df = pd.read_csv(geo_file_path)

# Display the first few rows of the DataFrame
geopolitical_distance_df.head()

,Unnamed: 0,ccode,session,NVotesAll,IdealPointAll,QO%All,Q5%All,Q10%All,Q50%All,Q90%All,Q95%All,Q100%All,iso3c,Countryname,USAgree,RUSSAgree,BrazilAgree,ChinaAgree,IndiaAgree,IsraelAgree
0,1,2,1,42,1.676350,1.099770,1.339545,1.404822,1.668589,1.958060,2.039101,2.490737,USA,United States,1.0,0.214286,0.642857,NaN,0.476191,NaN
1,2,2,2,38,1.975167,1.290319,1.559735,1.650037,1.951857,2.325626,2.488103,2.900903,USA,United States,1.0,0.263158,0.842105,NaN,0.297297,NaN
2,3,2,3,103,1.886102,1.372502,1.536494,1.602467,1.875287,2.168638,2.266258,2.562289,USA,United States,1.0,0.127451,0.776699,NaN,0.370000,0.166667
3,4,2,4,63,1.753212,1.279482,1.497219,1.549291,1.745286,1.945309,2.007389,2.251220,USA,United States,1.0,0.111111,0.539682,NaN,0.365079,0.516129
4,5,2,5,53,1.620488,0.843403,1.253614,1.333876,1.613809,1.926375,1.991641,2.423023,USA,United States,1.0,0.173077,0.811321,NaN,0.509434,0.604167

In [28]:
# Select the rows with the most recent session for each country (iso3c)
most_recent_sessions = geopolitical_distance_df.loc[geopolitical_distance_df.groupby('iso3c')['session'].idxmax()]

# Display the resulting DataFrame
most_recent_sessions.head()

,Unnamed: 0,ccode,session,NVotesAll,IdealPointAll,QO%All,Q5%All,Q10%All,Q50%All,Q90%All,Q95%All,Q100%All,iso3c,Countryname,USAgree,RUSSAgree,BrazilAgree,ChinaAgree,IndiaAgree,IsraelAgree
9122,9123,700,78,45,-0.512966,-1.328968,-0.904898,-0.800721,-0.498235,-0.244569,-0.174333,0.073742,AFG,Afghanistan,0.222222,0.488889,0.931818,0.733333,0.644444,0.177778
6974,6975,540,78,83,-0.557160,-1.172840,-0.787879,-0.723514,-0.552372,-0.373036,-0.332894,-0.132234,AGO,Angola,0.231707,0.536585,0.913580,0.691358,0.719512,0.197531
3652,3653,339,78,87,1.194305,0.820950,0.993311,1.039627,1.194556,1.351502,1.388737,1.609251,ALB,Albania,0.604651,0.360465,0.464286,0.388235,0.411765,0.500000
2972,2973,232,78,87,0.868780,0.572980,0.715955,0.746721,0.870667,0.997112,1.030072,1.153604,AND,Andorra,0.523256,0.313953,0.595238,0.435294,0.435294,0.428571
8992,8993,696,78,87,-0.663375,-1.171983,-0.884115,-0.831134,-0.657413,-0.500234,-0.458424,-0.159053,ARE,United Arab Emirates,0.209302,0.534884,0.880952,0.752941,0.729412,0.226190

In [29]:
# Rename the column 'countrycode_1' to 'iso3c' for consistency
most_recent_results.rename(columns={'countrycode_1': 'iso3c'}, inplace=True)

# Display the updated DataFrame
most_recent_results.head()

      year iso3c countrycode_2  cultdist  cultdist_std  n_questions
6     2021   ALB           ALB  0.261209     -3.455396          320
818   2021   AND           ALB  0.322753     -0.603146          160
1630  2021   ARG           ALB  0.318365     -0.795609          276
2442  2021   ARM           ALB  0.301791     -1.535909          300
3254  2021   AUS           ALB  0.348296      0.491817          207

In [30]:
merged_df = pd.merge(most_recent_results, most_recent_sessions, on='iso3c', how='inner')

merged_df.head()

,year,iso3c,countrycode_2,cultdist,cultdist_std,n_questions,Unnamed: 0,ccode,session,NVotesAll,...,Q90%All,Q95%All,Q100%All,Countryname,USAgree,RUSSAgree,BrazilAgree,ChinaAgree,IndiaAgree,IsraelAgree
0,2021,ALB,ALB,0.261209,-3.455396,320,3653,339,78,87,...,1.351502,1.388737,1.609251,Albania,0.604651,0.360465,0.464286,0.388235,0.411765,0.500000
1,2021,AND,ALB,0.322753,-0.603146,160,2973,232,78,87,...,0.997112,1.030072,1.153604,Andorra,0.523256,0.313953,0.595238,0.435294,0.435294,0.428571
2,2021,ARG,ALB,0.318365,-0.795609,276,2258,160,78,87,...,0.107453,0.137934,0.252694,Argentina,0.348837,0.523256,0.845238,0.658824,0.682353,0.309524
3,2021,ARM,ALB,0.301791,-1.535909,300,4537,371,78,82,...,0.199233,0.228422,0.353466,Armenia,0.246914,0.555556,0.721519,0.687500,0.712500,0.189873
4,2021,AUS,ALB,0.348296,0.491817,207,10737,900,78,87,...,1.491678,1.535722,1.696726,Australia,0.627907,0.313953,0.452381,0.376471,0.364706,0.547619

In [31]:
# Define the paths to the JSON files
organization_json_path = './data/cordis-HORIZONprojects-json/organization.json'
project_json_path = './data/cordis-HORIZONprojects-json/project.json'

# Load the JSON files into DataFrames
organization_df = pd.read_json(organization_json_path)
project_df = pd.read_json(project_json_path)

# Display the first few rows of each DataFrame
print("Organization DataFrame:")
organization_df.head()

Organization DataFrame:

,SME,active,activityType,city,contactForm,contentUpdateDate,country,ecContribution,endOfParticipation,geolocation,...,organizationURL,postCode,projectAcronym,projectID,rcn,role,shortName,street,totalCost,vatNumber
0,false,,REC,Antananarivo,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,MG,,false,"-18.7920779,47.7823214",...,,101,PvSeroRDT,101159220,1947090,associatedPartner,IPM,Ambatofotsikely - Avaradoha,0,
1,false,,REC,Dakar,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,SN,1777625,false,"14.693425,-17.447938",...,,DAKAR,PvSeroRDT,101159220,1906512,participant,,AVENUE PASTEUR 36,1777625,
2,false,,REC,Addis Ababa,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,ET,272174.38,false,"9.0,38.75",...,,1005,PvSeroRDT,101159220,1975141,participant,,JIMMA ROAD ALERT COMPOUND,272174.38,
3,false,,HES,London,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,UK,,false,"51.5207316,-0.1294867",...,http://www.lshtm.ac.uk/,WC1E 7HT,PvSeroRDT,101159220,1906028,associatedPartner,LSHTM,KEPPEL STREET,0,GB233756066
4,false,,OTH,Geneve,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,CH,,false,"46.221901,6.148001732215738",...,http://www.finddiagnostics.org/,1202,PvSeroRDT,101159220,1906308,associatedPartner,"FIND, the global alliance for diagnostics","CAMPUS BIOTECH, CHEMIN DES MINES 9",0,

In [32]:
print("\nProject DataFrame:")
project_df.head()

Project DataFrame:

,acronym,contentUpdateDate,ecMaxContribution,ecSignatureDate,endDate,frameworkProgramme,fundingScheme,grantDoi,id,legalBasis,masterCall,nature,objective,rcn,startDate,status,subCall,title,topics,totalCost
0,PvSeroRDT,2024-12-24 11:18:48,4062396.23,2024-12-09,2030-01-31,HORIZON,HORIZON-JU-RIA,10.3030/101159220,101159220,HORIZON.2.1,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,,Plasmodium vivax is considered the most diffic...,268210,2025-02-01,SIGNED,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,A point-of-care serological rapid diagnostic t...,HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage,4.062396e+06
1,BIOBoost,2022-12-01 14:09:06,500000.00,2022-11-25,2025-01-31,HORIZON,HORIZON-CSA,10.3030/101096150,101096150,HORIZON.3.2,HORIZON-EIE-2022-CONNECT-01,,The overall objectives of the BIOBoost project...,243343,2023-02-01,SIGNED,HORIZON-EIE-2022-CONNECT-01,Boosting innovation agencies for bioeconomy va...,HORIZON-EIE-2022-CONNECT-01-01,0.000000e+00
2,GlycanTrigger,2022-12-11 19:02:29,6771571.00,2022-12-05,2028-12-31,HORIZON,HORIZON-RIA,10.3030/101093997,101093997,HORIZON.2.1,HORIZON-HLTH-2022-STAYHLTH-02,,Chronic inflammation underlies several disease...,243439,2023-01-01,SIGNED,HORIZON-HLTH-2022-STAYHLTH-02,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,HORIZON-HLTH-2022-STAYHLTH-02-01,6.771571e+06
3,CHIKVAX_CHIM,2023-09-19 19:01:01,70000000.00,2023-06-15,2028-11-30,HORIZON,HORIZON-COFUND,10.3030/101126531,101126531,HORIZON.2.1,HORIZON-HLTH-2022-CEPI-15-IBA,,A Framework Partnership Agreement (FPA) betwee...,256925,2023-06-01,SIGNED,HORIZON-HLTH-2022-CEPI-15-IBA,Late-stage clinical development of Chikungunya...,HORIZON-HLTH-2022-CEPI-15-01-IBA,1.000000e+08
4,The Oater,2023-07-11 15:45:49,75000.00,2023-06-05,2023-12-31,HORIZON,HORIZON-CSA,10.3030/101113979,101113979,HORIZON.3.2,HORIZON-EIE-2022-SCALEUP-02,,The Oater is a female-founded food tech start-...,253030,2023-07-01,CLOSED,HORIZON-EIE-2022-SCALEUP-02,The Oater develops a compact machine for hyper...,HORIZON-EIE-2022-SCALEUP-02-02,0.000000e+00

In [33]:
# Display the first few rows of each DataFrame
print("Organization DataFrame:")
organization_df.head()

Organization DataFrame:

,SME,active,activityType,city,contactForm,contentUpdateDate,country,ecContribution,endOfParticipation,geolocation,...,organizationURL,postCode,projectAcronym,projectID,rcn,role,shortName,street,totalCost,vatNumber
0,false,,REC,Antananarivo,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,MG,,false,"-18.7920779,47.7823214",...,,101,PvSeroRDT,101159220,1947090,associatedPartner,IPM,Ambatofotsikely - Avaradoha,0,
1,false,,REC,Dakar,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,SN,1777625,false,"14.693425,-17.447938",...,,DAKAR,PvSeroRDT,101159220,1906512,participant,,AVENUE PASTEUR 36,1777625,
2,false,,REC,Addis Ababa,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,ET,272174.38,false,"9.0,38.75",...,,1005,PvSeroRDT,101159220,1975141,participant,,JIMMA ROAD ALERT COMPOUND,272174.38,
3,false,,HES,London,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,UK,,false,"51.5207316,-0.1294867",...,http://www.lshtm.ac.uk/,WC1E 7HT,PvSeroRDT,101159220,1906028,associatedPartner,LSHTM,KEPPEL STREET,0,GB233756066
4,false,,OTH,Geneve,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,CH,,false,"46.221901,6.148001732215738",...,http://www.finddiagnostics.org/,1202,PvSeroRDT,101159220,1906308,associatedPartner,"FIND, the global alliance for diagnostics","CAMPUS BIOTECH, CHEMIN DES MINES 9",0,

In [34]:
# Define a mapping for special cases
special_cases = {
    'UK': 'GBR',  # United Kingdom
    'EL': 'GRC',  # Greece
    'XK': 'XKX',  # Kosovo (not officially ISO-recognized but often used)
    # Add other special cases as needed
}

# Function to convert alpha-2 country codes to alpha-3, including special cases
def convert_to_iso3(alpha2_code):
    if alpha2_code in special_cases:
        return special_cases[alpha2_code]
    try:
        return pycountry.countries.get(alpha_2=alpha2_code).alpha_3
    except AttributeError:
        return None

# Apply the conversion to the 'country' column in the organization DataFrame
organization_df['iso3c'] = organization_df['country'].apply(convert_to_iso3)

# Find rows where the conversion failed (iso3c is None)
missing_iso3 = organization_df[organization_df['iso3c'].isnull()]

# Display the problematic rows
print("Rows with missing iso3c:")
missing_iso3[['country','city','geolocation','iso3c']].head()

Rows with missing iso3c:

      country      city                              geolocation iso3c
2004           Bethesda      51.97298191170089,4.255199735681509  None
4353           Bethesda                     40.423876,-86.921173  None
4652           Bethesda                        43.491418,5.33329  None
21533           Crawley  51.132867859266646,-0.18120416288818297  None
60791          Bethesda                     40.423876,-86.921173  None

In [35]:
# Find rows where the conversion failed (iso3c is None)
missing_iso3 = organization_df[organization_df['iso3c'].isnull()]

# Display the problematic rows
missing_iso3.head()

,SME,active,activityType,city,contactForm,contentUpdateDate,country,ecContribution,endOfParticipation,geolocation,...,postCode,projectAcronym,projectID,rcn,role,shortName,street,totalCost,vatNumber,iso3c
2004,True,,PRC,Bethesda,https://ec.europa.eu/info/funding-tenders/oppo...,2023-04-05 13:27:01,,,false,"51.97298191170089,4.255199735681509",...,,rePLANT,101081581,1978471,associatedPartner,,,0,,None
4353,false,,PRC,Bethesda,https://ec.europa.eu/info/funding-tenders/oppo...,2022-09-02 17:35:23,,,false,"40.423876,-86.921173",...,,STALSUns,101063992,1976477,associatedPartner,,,,,None
4652,false,,OTH,Bethesda,https://ec.europa.eu/info/funding-tenders/oppo...,2022-09-04 03:00:02,,,false,"43.491418,5.33329",...,,WaterScapes,101065058,1976290,associatedPartner,,,0,,None
21533,false,,,Crawley,https://ec.europa.eu/info/funding-tenders/oppo...,2023-09-20 16:28:07,,,false,"51.132867859266646,-0.18120416288818297",...,9DF123,GEESE,101114611,1984151,associatedPartner,,"The VHQ, Fleming Way, RH10",0,,None
60791,false,,PRC,Bethesda,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-16 15:33:33,,,false,"40.423876,-86.921173",...,,ATENEA,101178250,1976477,associatedPartner,,,0,,None

In [36]:
from geopy.geocoders import Nominatim

# Initialize the geolocator
geolocator = Nominatim(user_agent="geoapi")

# Function to get the country from geolocation
def get_country_from_geolocation(geolocation):
    try:
        # Split the geolocation into latitude and longitude
        lat, lon = map(float, geolocation.split(','))
        location = geolocator.reverse((lat, lon), language='en')
        return location.raw['address']['country_code'].upper()  # Return alpha-2 country code
    except Exception as e:
        print(f"Error processing geolocation {geolocation}: {e}")
        return None

# Apply the function to rows with missing iso3c
missing_iso3['country_from_geo'] = missing_iso3['geolocation'].apply(get_country_from_geolocation)

# Display the updated rows
missing_iso3[['country', 'city', 'geolocation', 'country_from_geo']]

Error processing geolocation 51.97298191170089,4.255199735681509: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)
Error processing geolocation 40.423876,-86.921173: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)
Error processing geolocation 43.491418,5.33329: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)
Error processing geolocation 51.132867859266646,-0.18120416288818297: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)
Error processing geolocation 40.423876,-86.921173: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)

/var/folders/h9/cypcrhp14dn4gqqq118p8dyh0000gn/T/ipykernel_5597/267265273.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_iso3['country_from_geo'] = missing_iso3['geolocation'].apply(get_country_from_geolocation)

,country,city,geolocation,country_from_geo
2004,,Bethesda,"51.97298191170089,4.255199735681509",None
4353,,Bethesda,"40.423876,-86.921173",None
4652,,Bethesda,"43.491418,5.33329",None
21533,,Crawley,"51.132867859266646,-0.18120416288818297",None
60791,,Bethesda,"40.423876,-86.921173",None

In [37]:
# Drop rows where iso3c is None
organization_df = organization_df[organization_df['iso3c'].notnull()]

# Verify the updated DataFrame
print("Rows remaining after dropping missing iso3c:")
organization_df.head()

Rows remaining after dropping missing iso3c:

,SME,active,activityType,city,contactForm,contentUpdateDate,country,ecContribution,endOfParticipation,geolocation,...,postCode,projectAcronym,projectID,rcn,role,shortName,street,totalCost,vatNumber,iso3c
0,false,,REC,Antananarivo,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,MG,,false,"-18.7920779,47.7823214",...,101,PvSeroRDT,101159220,1947090,associatedPartner,IPM,Ambatofotsikely - Avaradoha,0,,MDG
1,false,,REC,Dakar,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,SN,1777625,false,"14.693425,-17.447938",...,DAKAR,PvSeroRDT,101159220,1906512,participant,,AVENUE PASTEUR 36,1777625,,SEN
2,false,,REC,Addis Ababa,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,ET,272174.38,false,"9.0,38.75",...,1005,PvSeroRDT,101159220,1975141,participant,,JIMMA ROAD ALERT COMPOUND,272174.38,,ETH
3,false,,HES,London,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,UK,,false,"51.5207316,-0.1294867",...,WC1E 7HT,PvSeroRDT,101159220,1906028,associatedPartner,LSHTM,KEPPEL STREET,0,GB233756066,GBR
4,false,,OTH,Geneve,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,CH,,false,"46.221901,6.148001732215738",...,1202,PvSeroRDT,101159220,1906308,associatedPartner,"FIND, the global alliance for diagnostics","CAMPUS BIOTECH, CHEMIN DES MINES 9",0,,CHE

In [40]:
# Merge the organization_df with merged_df on the 'iso3c' column
organization_with_country_data = pd.merge(organization_df, merged_df, on='iso3c', how='inner')

# Display the resulting DataFrame
organization_with_country_data.head()

,SME,active,activityType,city,contactForm,contentUpdateDate,country,ecContribution,endOfParticipation,geolocation,...,Q90%All,Q95%All,Q100%All,Countryname,USAgree,RUSSAgree,BrazilAgree,ChinaAgree,IndiaAgree,IsraelAgree
0,false,,REC,Addis Ababa,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,ET,272174.38,false,"9.0,38.75",...,-0.319783,-0.273615,-0.071351,Ethiopia,0.219512,0.548781,0.900000,0.691358,0.743902,0.212500
1,false,,HES,London,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,UK,,false,"51.5207316,-0.1294867",...,2.237283,2.288665,2.522697,United Kingdom,0.717647,0.341176,0.428571,0.333333,0.380952,0.638554
2,false,,OTH,Geneve,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,CH,,false,"46.221901,6.148001732215738",...,0.835157,0.859114,1.035163,Switzerland,0.453488,0.325581,0.583333,0.458823,0.458823,0.404762
3,false,,REC,Paris,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,FR,2012596.85,false,"48.8420154,2.3129099",...,1.739512,1.781530,1.992883,France,0.627907,0.383721,0.476191,0.364706,0.411765,0.571429
4,True,,PRC,YORK,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,UK,,false,,...,2.237283,2.288665,2.522697,United Kingdom,0.717647,0.341176,0.428571,0.333333,0.380952,0.638554

In [46]:
# Get unique iso3c values from both DataFrames
countries_in_merged = set(merged_df['iso3c'].unique())
countries_in_organizations = set(organization_df['iso3c'].unique())

# Countries in merged_df but not in organization_df
countries_only_in_merged = countries_in_merged - countries_in_organizations
print("Countries in merged_df but not in organization_df:")
print(countries_only_in_merged)

# Countries in organization_df but not in merged_df
countries_only_in_organizations = countries_in_organizations - countries_in_merged
print("\nCountries in organization_df but not in merged_df:")
print(countries_only_in_organizations)

Countries in merged_df but not in organization_df:
{'MMR', 'YEM', 'TTO', 'BLR', 'RUS'}

Countries in organization_df but not in merged_df:
{'FRO', 'GIB', 'COD', 'VAT', 'AIA', 'MAC', 'HKG', 'KHM', 'BEN', 'MHL', 'LKA', 'PSE', 'CAF', 'GIN', 'ARE', 'NAM', 'TGO', 'BTN', 'COG', 'LAO', 'BES', 'GNB', 'LBR', 'CMR', 'STP', 'LIE', 'CUB', 'TKM', 'GNQ', 'IMN', 'CPV', 'NPL', 'PNG', 'BDI', 'MDG', 'FJI', 'DJI', 'PRY', 'ABW', 'PYF', 'CIV', 'BWA', 'MCO', 'GUM', 'AGO', 'GMB', 'LSO', 'GAB', 'MRT', 'AFG', 'SUR', 'SWZ', 'NER', 'CRI', 'NCL', 'MWI', 'TCD', 'XKX', 'SEN', 'MOZ', 'GRL', 'SRB', 'PAN', 'SDN', 'SLE', 'MUS'}

It's understandable that these countries are not included because they are either not part of the EU research ecosystem, not UN Members, or not surveyed in the World values survey.

Territories or Special Administrative Regions:

HKG (Hong Kong), MAC (Macau), GIB (Gibraltar), FRO (Faroe Islands), BES (Caribbean Netherlands), PYF (French Polynesia), GUM (Guam), NCL (New Caledonia) are territories or regions that may not have independent representation in UN voting or WVS data.
Small or Remote Countries:

LIE (Liechtenstein), MCO (Monaco), BTN (Bhutan), STP (São Tomé and Príncipe), MDG (Madagascar), MHL (Marshall Islands), CPV (Cape Verde), SWZ (Eswatini) may lack data due to their size or logistical challenges.
Conflict Zones or Fragile States:

XKX (Kosovo), PSE (Palestine), SDN (Sudan), CAF (Central African Republic), SLE (Sierra Leone), AFG (Afghanistan), COD (Democratic Republic of Congo) may lack data due to political instability or conflict.
Developing Countries:

Countries like BEN (Benin), TGO (Togo), NER (Niger), MOZ (Mozambique), MWI (Malawi), DJI (Djibouti), BDI (Burundi) may not have participated in WVS due to limited resources or prioritization of other surveys.

In [51]:
import random

# Add a new column 'topic' with random letters from A-J
project_df['topic'] = [random.choice('ABCDEFGHIJKLMOPQRSTUVWXYZ') for _ in range(len(project_df))]

# Display the updated DataFrame
project_df.head()

,acronym,contentUpdateDate,ecMaxContribution,ecSignatureDate,endDate,frameworkProgramme,fundingScheme,grantDoi,id,legalBasis,...,nature,objective,rcn,startDate,status,subCall,title,topics,totalCost,topic
0,PvSeroRDT,2024-12-24 11:18:48,4062396.23,2024-12-09,2030-01-31,HORIZON,HORIZON-JU-RIA,10.3030/101159220,101159220,HORIZON.2.1,...,,Plasmodium vivax is considered the most diffic...,268210,2025-02-01,SIGNED,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,A point-of-care serological rapid diagnostic t...,HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage,4.062396e+06,F
1,BIOBoost,2022-12-01 14:09:06,500000.00,2022-11-25,2025-01-31,HORIZON,HORIZON-CSA,10.3030/101096150,101096150,HORIZON.3.2,...,,The overall objectives of the BIOBoost project...,243343,2023-02-01,SIGNED,HORIZON-EIE-2022-CONNECT-01,Boosting innovation agencies for bioeconomy va...,HORIZON-EIE-2022-CONNECT-01-01,0.000000e+00,P
2,GlycanTrigger,2022-12-11 19:02:29,6771571.00,2022-12-05,2028-12-31,HORIZON,HORIZON-RIA,10.3030/101093997,101093997,HORIZON.2.1,...,,Chronic inflammation underlies several disease...,243439,2023-01-01,SIGNED,HORIZON-HLTH-2022-STAYHLTH-02,GLYCANS AS MASTER TRIGGERS OF HEALTH TO INTEST...,HORIZON-HLTH-2022-STAYHLTH-02-01,6.771571e+06,C
3,CHIKVAX_CHIM,2023-09-19 19:01:01,70000000.00,2023-06-15,2028-11-30,HORIZON,HORIZON-COFUND,10.3030/101126531,101126531,HORIZON.2.1,...,,A Framework Partnership Agreement (FPA) betwee...,256925,2023-06-01,SIGNED,HORIZON-HLTH-2022-CEPI-15-IBA,Late-stage clinical development of Chikungunya...,HORIZON-HLTH-2022-CEPI-15-01-IBA,1.000000e+08,T
4,The Oater,2023-07-11 15:45:49,75000.00,2023-06-05,2023-12-31,HORIZON,HORIZON-CSA,10.3030/101113979,101113979,HORIZON.3.2,...,,The Oater is a female-founded food tech start-...,253030,2023-07-01,CLOSED,HORIZON-EIE-2022-SCALEUP-02,The Oater develops a compact machine for hyper...,HORIZON-EIE-2022-SCALEUP-02-02,0.000000e+00,E

Join all the data together

In [52]:
# Merge the two DataFrames on the specified key fields
merged_organization_project_df = pd.merge(
    organization_with_country_data,
    project_df,
    left_on='projectID',
    right_on='id',
    how='inner'
)

# Display the first few rows of the resulting DataFrame
merged_organization_project_df.head()

,SME,active,activityType,city,contactForm,contentUpdateDate_x,country,ecContribution,endOfParticipation,geolocation,...,nature,objective,rcn_y,startDate,status,subCall,title,topics,totalCost_y,topic
0,false,,REC,Addis Ababa,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,ET,272174.38,false,"9.0,38.75",...,,Plasmodium vivax is considered the most diffic...,268210,2025-02-01,SIGNED,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,A point-of-care serological rapid diagnostic t...,HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage,4062396.23,F
1,false,,HES,London,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,UK,,false,"51.5207316,-0.1294867",...,,Plasmodium vivax is considered the most diffic...,268210,2025-02-01,SIGNED,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,A point-of-care serological rapid diagnostic t...,HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage,4062396.23,F
2,false,,OTH,Geneve,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,CH,,false,"46.221901,6.148001732215738",...,,Plasmodium vivax is considered the most diffic...,268210,2025-02-01,SIGNED,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,A point-of-care serological rapid diagnostic t...,HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage,4062396.23,F
3,false,,REC,Paris,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,FR,2012596.85,false,"48.8420154,2.3129099",...,,Plasmodium vivax is considered the most diffic...,268210,2025-02-01,SIGNED,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,A point-of-care serological rapid diagnostic t...,HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage,4062396.23,F
4,True,,PRC,YORK,https://ec.europa.eu/info/funding-tenders/oppo...,2024-12-24 11:18:48,UK,,false,,...,,Plasmodium vivax is considered the most diffic...,268210,2025-02-01,SIGNED,HORIZON-JU-GH-EDCTP3-2023-02-two-stage,A point-of-care serological rapid diagnostic t...,HORIZON-JU-GH-EDCTP3-2023-02-02-two-stage,4062396.23,F

In [53]:
merged_organization_project_df.columns

Index(['SME', 'active', 'activityType', 'city', 'contactForm',
       'contentUpdateDate_x', 'country', 'ecContribution',
       'endOfParticipation', 'geolocation', 'name', 'netEcContribution',
       'nutsCode', 'order', 'organisationID', 'organizationURL', 'postCode',
       'projectAcronym', 'projectID', 'rcn_x', 'role', 'shortName', 'street',
       'totalCost_x', 'vatNumber', 'iso3c', 'year', 'countrycode_2',
       'cultdist', 'cultdist_std', 'n_questions', 'Unnamed: 0', 'ccode',
       'session', 'NVotesAll', 'IdealPointAll', 'QO%All', 'Q5%All', 'Q10%All',
       'Q50%All', 'Q90%All', 'Q95%All', 'Q100%All', 'Countryname', 'USAgree',
       'RUSSAgree', 'BrazilAgree', 'ChinaAgree', 'IndiaAgree', 'IsraelAgree',
       'acronym', 'contentUpdateDate_y', 'ecMaxContribution',
       'ecSignatureDate', 'endDate', 'frameworkProgramme', 'fundingScheme',
       'grantDoi', 'id', 'legalBasis', 'masterCall', 'nature', 'objective',
       'rcn_y', 'startDate', 'status', 'subCall', 'title', 'topics',
       'totalCost_y', 'topic'],
      dtype='object')

In [54]:
# Define the file path for export
export_path = './data/merged_organization_project_data.csv'

# Export the DataFrame to a CSV file
merged_organization_project_df.to_csv(export_path, index=False)

print(f"Dataset exported to {export_path}")

Dataset exported to ./data/merged_organization_project_data.csv